
# Site settings
title: Gautam Ajay
name: Gautam Ajay
subtitle: A compilation of my ideas and beliefs and interests and runons. 
email: gautam.ajay@gmail.com
description: A website with a mind of its own
baseurl: ""
disqus_baseurl: "https://gautam-ajay.github.io/"
permalink: :title
avatar: "/assets/headshot.jpg"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Gautam Ajay"


# External gems
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag

exclude:
  - "/vendor/"

# Collections
collections:
  - talks
